---
- name:
  hosts: all
  become: true
  vars:
    docker_users:
      - panda
      - vagrant
  roles:
    - user
    - rola
    - geerlingguy.docker
    - christiangda.awscli
    - christiangda.awscli_configure
    - diodonfrost.terraform
